// Generated by scripts/generate_native.py; do not edit.
#pragma once

#include "../port_forge/src/arch/m68k/alu.hpp"
#include "../port_forge/src/platform/mac68k/executor.hpp"

namespace simant::mac68k::generated {

// mac.code.1.4: ORI.B #$12,D0 (original bytes 00 00 03 12).
inline pf::mac68k::NativeBlockResult mac_code_1_4(
    pf::mac68k::Machine& machine) {
    const uint32_t low = pf::m68k::alu::logic(
        machine.cpu.cpu,
        (machine.cpu.cpu.d[0] & 0xFFu) | 0x12u, 1);
    machine.cpu.cpu.d[0] =
        (machine.cpu.cpu.d[0] & 0xFFFFFF00u) | low;
    return {
        (machine.cpu.cpu.pc + 4u) & pf::m68k::kAddressMask,
        1, 8,
    };
}

// mac.code.2.2906: generated linear MPW leaf function.
inline pf::mac68k::NativeBlockResult mac_code_2_2906(
    pf::mac68k::Machine& machine) {
    auto& cpu = machine.cpu.cpu;
    cpu.a[7] = (cpu.a[7] - 4u) & pf::m68k::kAddressMask;
    machine.cpu.write32(cpu.a[7], cpu.a[6]);
    cpu.a[6] = cpu.a[7];
    cpu.a[0] = machine.cpu.read32(
        (cpu.a[6] + 8u) & pf::m68k::kAddressMask);
    cpu.d[0] = machine.cpu.read32(
        (cpu.a[0] + 2u) & pf::m68k::kAddressMask);
    pf::m68k::alu::logic(cpu, cpu.d[0], 4);
    cpu.a[7] = cpu.a[6];
    cpu.a[6] = machine.cpu.read32(cpu.a[7]);
    cpu.a[7] = (cpu.a[7] + 4u) & pf::m68k::kAddressMask;
    const uint32_t next_pc =
        machine.cpu.read32(cpu.a[7]) & pf::m68k::kAddressMask;
    cpu.a[7] = (cpu.a[7] + 4u) & pf::m68k::kAddressMask;
    return {next_pc, 5, 76};
}

inline void install(
    pf::mac68k::Executor& executor) {
    executor.native_hooks().register_block(
        {1, 4},
        {
        0x00, 0x00, 0x03, 0x12,
        },
        &mac_code_1_4);
    executor.native_hooks().register_linear_function(
        {2, 2906},
        {
        0x4E, 0x56, 0x00, 0x00,
        0x20, 0x6E, 0x00, 0x08,
        0x20, 0x28, 0x00, 0x02,
        0x4E, 0x5E, 0x4E, 0x75,
        },
        &mac_code_2_2906);
}

} // namespace simant::mac68k::generated
