#!/usr/bin/env python3
"""Build and verify SimAnt's first source-bound Mac68k native instruction."""

from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PORT_FORGE = ROOT / "port_forge"
LIFT_PLAN = ROOT / "artifacts" / "analysis" / "mac_static_lift_plan.json"
SOURCE = ROOT / "tests" / "native_entry_units.cpp"
OUTPUT = ROOT / "build" / "native_entry_units.exe"


def verify_source_binding() -> None:
    plan = json.loads(LIFT_PLAN.read_text(encoding="utf-8"))
    if plan.get("format") != "portforge-mac68k-lift-plan-v1":
        raise RuntimeError("native entry test requires the current Mac lift plan")
    matches = [
        instruction
        for segment in plan.get("segments", [])
        for instruction in segment.get("instructions", [])
        if instruction.get("code_identity") == "mac.code.1.4"
    ]
    if len(matches) != 1 or matches[0].get("bytes") != "00000312":
        raise RuntimeError(
            "mac.code.1.4 no longer matches generated bytes 00000312"
        )
    if matches[0].get("flow") != "fallthrough" or matches[0].get("length") != 4:
        raise RuntimeError("mac.code.1.4 is no longer one fallthrough instruction")


def load_build_module():
    sys.path.insert(0, str(PORT_FORGE))
    spec = importlib.util.spec_from_file_location(
        "portforge_build", PORT_FORGE / "build.py"
    )
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load PortForge build support")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def main() -> int:
    verify_source_binding()
    build = load_build_module()
    command = [
        build.CXX,
        *build.CXXFLAGS,
        str(SOURCE),
        "-o",
        str(OUTPUT),
    ]
    build.ensure(
        OUTPUT,
        command,
        explicit_inputs=(LIFT_PLAN,),
    )
    subprocess.run([str(OUTPUT)], cwd=ROOT, check=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
